prompt_generator_beta_v0 = {
    "name": "prompt_generator",
    "description": (
        "Role : User. "
        "Context:  You are a user who wants to consult outfit using a fashion recommendation system. "
        "One single output example : 'Today I want a casual outfit for dating with my girlfriend, the outfit should looks formal, and have a good breathability because now it's summer. In addtion, I want their are some dinoaur print on shirt.'. "
        "Output: A list of 10 prompts in different aspects, contain three or more of these attributes for each prompt: color, style, material, fit, occasion, seasonality, pattern, unique design, and part they desired(implicitly). And you should cover general patterns in these generated prompt."
        "Usage: Use for a synthetic user prompt. "
    ),
    "parameters" : {
        "type": "object",
        "properties": {
            "prompts" : {
                "type": "array",
                "items" : {
                    "type" : "string",
                    "description" : "Prompt in different aspects."
                }
            }
        },
        "description": "Response must contain a list of 10 prompts in different aspects."
        },

    "required": ["prompts"],
    }

sythetic_prompts = {
  "synthetic_prompts_list": [
    "Today I want a casual outfit for dating with my girlfriend, the outfit should looks formal, and have a good breathability because now it's summer. In addtion, I want their are some dinoaur print on shirt.",
    "I need a vibrant summer outfit for a beach party, preferably in bright colors with a lightweight fabric and a relaxed fit.",
    "Looking for a formal business suit in navy blue, tailored fit, made from wool, suitable for autumn meetings.",
    "Want a cozy winter look with a chunky knit sweater in earthy tones, paired with slim-fit jeans and a unique graphic pattern.",
    "Seeking a sporty outfit for running, featuring moisture-wicking material, bright accents, and a comfortable fit.",
    "Desire an elegant evening gown in deep red, with a flowing silhouette and intricate lace details for a gala event.",
    "Need a casual spring ensemble with pastel colors, breathable cotton, and a relaxed fit for daily outings.",
    "Looking for a retro-inspired outfit with bold patterns, high-waisted pants, and a fitted top for a themed party.",
    "Want a minimalist outfit in monochrome shades, made from sustainable materials, with a sleek and modern cut.",
    "Seeking a trendy streetwear look with oversized hoodies, distressed denim, and statement accessories for urban settings.",
    "Desire a timeless classic outfit with neutral colors, tailored fit, and premium fabrics suitable for any occasion.",
    "I’m looking for a bohemian summer dress in floral patterns, lightweight fabric, and a flowy fit for music festivals.",
    "Need a professional attire in charcoal gray, slim fit, made from breathable linen for office environments.",
    "Want a layered autumn outfit with earth tones, cozy materials like fleece, and a relaxed silhouette for outdoor activities.",
    "Seeking a party outfit with metallic accents, sleek design, and a fitted style for night events.",
    "Desire a versatile winter coat in black, insulated material, and a tailored fit for daily commuting.",
    "Looking for a casual weekend look with denim shorts, vibrant colors, and a loose fit for comfort.",
    "Want a sophisticated cocktail dress in navy, with a fitted waist and unique embroidery for evening parties.",
    "Need a lightweight spring jacket in pastel shades, breathable fabric, and a relaxed fit for unpredictable weather.",
    "Seeking a trendy athleisure outfit with bold colors, stretchy material, and a comfortable fit for workouts.",
    "Desire a classic trench coat in beige, waterproof material, and a tailored fit for rainy days.",
    "I’m looking for a festive holiday outfit with rich colors, luxurious fabrics, and a formal style for celebrations.",
    "Need a summer romper in bright patterns, breathable cotton, and a relaxed fit for casual outings.",
    "Want a sleek black evening suit with a modern cut, made from fine wool, suitable for formal events.",
    "Seeking a layered spring outfit with light fabrics, complementary colors, and a comfortable fit for transitions.",
    "Desire a unique festival outfit with vibrant prints, unconventional materials, and an oversized fit for comfort.",
    "Looking for a minimalist winter sweater in neutral tones, made from cashmere, with a slim fit for elegance.",
    "Want a sporty chic outfit with bold colors, moisture-wicking fabric, and a tailored fit for active days.",
    "Need a romantic summer dress in soft hues, lightweight material, and a flowy silhouette for date nights.",
    "Seeking a business casual look with earthy colors, breathable fabrics, and a relaxed fit for the office.",
    "Desire an edgy streetwear outfit with dark tones, distressed materials, and a loose fit for urban style.",
    "I’m looking for a comfortable loungewear set in pastel colors, soft fabric, and a relaxed fit for home.",
    "Need a formal black-tie attire with elegant design, luxurious material, and a tailored fit for gala events.",
    "Want a versatile transitional jacket in olive green, lightweight material, and a modern cut for changing seasons.",
    "Seeking a playful summer outfit with bright colors, breathable fabric, and a fitted style for casual fun.",
    "Desire a classic winter ensemble with neutral tones, warm materials, and a tailored fit for sophisticated looks.",
    "Looking for a trendy office outfit with bold accents, comfortable fabric, and a professional fit for daily wear.",
    "Want a chic evening top in jewel tones, unique patterns, and a flattering fit for nights out.",
    "Need a lightweight fall sweater in earthy colors, soft material, and a relaxed fit for layering.",
    "Seeking a modern casual outfit with monochrome shades, breathable fabric, and a slim fit for everyday use.",
    "Desire a bold party dress with vibrant colors, unique design elements, and a fitted silhouette for standout appearances.",
    "I’m looking for a sustainable spring outfit with eco-friendly materials, soft colors, and a comfortable fit for daily activities.",
    "Need a cozy autumn hoodie in warm tones, thick material, and a relaxed fit for cooler days.",
    "Want a sophisticated summer blazer in light colors, breathable fabric, and a tailored fit for smart casual events.",
    "Seeking a versatile winter accessory set with neutral colors, warm materials, and stylish designs for everyday use.",
    "Desire a unique festival hat in bright colors, lightweight material, and a comfortable fit for outdoor events.",
    "Looking for a classic denim jacket in blue, durable material, and a relaxed fit for layering.",
    "Want a sleek summer shorts in pastel shades, breathable fabric, and a comfortable fit for casual outings.",
    "Need a formal winter coat in black, insulated material, and a tailored fit for elegant warmth.",
    "Seeking a trendy spring skirt with floral patterns, lightweight fabric, and a flowy fit for daily wear.",
    "Desire a minimalist summer top in white, breathable material, and a relaxed fit for simplicity and comfort.",
    "I’m looking for a sporty winter outfit with bold colors, warm materials, and a comfortable fit for active days.",
    "Need a chic autumn scarf in earthy tones, soft fabric, and a versatile design for accessorizing.",
    "Want a casual summer t-shirt in vibrant colors, breathable cotton, and a relaxed fit for everyday use.",
    "Seeking a formal evening blazer in deep blue, luxurious material, and a tailored fit for sophisticated events.",
    "Desire a comfortable spring leggings in neutral colors, stretchy fabric, and a slim fit for versatility.",
    "Looking for a unique winter hat in bright patterns, warm material, and a stylish design for cold days.",
    "Want a trendy summer romper in bold colors, lightweight fabric, and a relaxed fit for casual outings.",
    "Need a professional autumn blazer in charcoal, breathable material, and a tailored fit for office wear.",
    "Seeking a cozy winter sweater in pastel tones, soft fabric, and a relaxed fit for warmth and comfort.",
    "Desire a stylish summer skirt in vibrant colors, lightweight material, and a flowy fit for casual events.",
    "I’m looking for a formal spring dress in soft hues, elegant design, and a fitted silhouette for special occasions.",
    "Need a versatile winter jacket in neutral colors, insulated material, and a modern cut for everyday use.",
    "Want a playful autumn top with unique patterns, warm fabric, and a relaxed fit for stylish layering.",
    "Seeking a minimalist summer shorts in monochrome shades, breathable material, and a comfortable fit for simplicity.",
    "Desire a bold winter coat in bright colors, durable fabric, and a tailored fit for standout warmth.",
    "Looking for a trendy spring outfit with pastel colors, lightweight materials, and a flattering fit for fresh looks.",
    "Want a cozy summer hoodie in soft tones, breathable fabric, and a relaxed fit for casual comfort.",
    "Need a formal autumn suit in deep green, tailored fit, and premium material for professional settings.",
    "Seeking a unique winter dress with intricate patterns, warm fabric, and a fitted silhouette for elegant warmth.",
    "Desire a stylish summer top in vibrant hues, lightweight material, and a flowy fit for breezy days.",
    "I’m looking for a casual spring jacket in earthy colors, breathable fabric, and a relaxed fit for everyday wear.",
    "Need a sophisticated winter scarf in neutral tones, warm material, and a classic design for versatile styling.",
    "Want a trendy autumn skirt with bold patterns, comfortable fabric, and a flattering fit for stylish looks.",
    "Seeking a minimalist summer dress in monochrome shades, lightweight material, and a sleek silhouette for simplicity.",
    "Desire a bold spring blazer in bright colors, tailored fit, and unique design elements for standout office wear.",
    "Looking for a cozy winter sweater in deep hues, soft fabric, and a relaxed fit for comfortable warmth.",
    "Want a stylish summer accessory set with vibrant colors, lightweight materials, and unique designs for added flair.",
    "Need a formal autumn coat in navy blue, insulated material, and a tailored fit for professional elegance.",
    "Seeking a versatile spring romper in pastel colors, breathable fabric, and a comfortable fit for easy wear.",
    "Desire a unique winter jacket with intricate patterns, warm material, and a modern cut for fashionable warmth.",
    "I’m looking for a casual summer hoodie in bright colors, lightweight fabric, and a relaxed fit for everyday comfort.",
    "Need a sophisticated autumn scarf in rich tones, soft material, and an elegant design for stylish layering.",
    "Want a trendy winter beanie in bold colors, warm fabric, and a unique design for standout cold-weather style.",
    "Seeking a minimalist spring top in neutral shades, breathable material, and a sleek fit for versatile looks.",
    "Desire a bold summer swimsuit with vibrant patterns, quick-dry material, and a flattering fit for beach outings.",
    "Looking for a cozy autumn cardigan in earthy tones, soft fabric, and a relaxed fit for comfortable layering.",
    "Want a stylish winter boots in dark colors, warm material, and a durable design for everyday wear.",
    "Need a formal spring blazer in light blue, tailored fit, and breathable fabric for professional settings.",
    "Seeking a unique summer hat with bright patterns, lightweight material, and a comfortable fit for sunny days.",
    "Desire a minimalist winter coat in black, insulated material, and a sleek design for elegant warmth.",
    "I’m looking for a casual spring dress in pastel colors, breathable fabric, and a relaxed fit for everyday wear.",
    "Need a sophisticated summer blazer in white, lightweight material, and a tailored fit for smart casual events.",
    "Want a trendy autumn boots in earthy tones, comfortable material, and a stylish design for fall fashion.",
    "Seeking a cozy winter sweater in neutral shades, soft fabric, and a relaxed fit for warmth and comfort.",
    "Desire a bold spring top with vibrant colors, lightweight material, and a flattering fit for fresh looks.",
    "Looking for a minimalist summer shorts in monochrome colors, breathable fabric, and a comfortable fit for simplicity.",
    "Want a stylish autumn jacket in deep green, warm material, and a tailored fit for seasonal elegance.",
    "Need a formal winter suit in navy blue, tailored fit, and premium material for professional events.",
    "Seeking a unique spring skirt with intricate patterns, lightweight fabric, and a flowy fit for stylish looks.",
    "Desire a cozy summer hoodie in soft colors, breathable material, and a relaxed fit for casual comfort.",
    "I’m looking for a casual winter coat in neutral tones, warm fabric, and a comfortable fit for everyday use.",
    "Need a sophisticated autumn scarf in rich colors, soft material, and a versatile design for stylish layering.",
    "Want a trendy spring dress with bold patterns, lightweight fabric, and a flattering fit for fresh fashion.",
    "Seeking a minimalist summer top in white, breathable material, and a sleek fit for simple elegance.",
    "Desire a bold winter beanie in vibrant colors, warm fabric, and a unique design for standout cold-weather style.",
    "Looking for a cozy autumn sweater in earthy tones, soft fabric, and a relaxed fit for comfortable warmth.",
    "Want a stylish spring blazer in pastel colors, lightweight material, and a tailored fit for professional settings.",
    "Need a formal summer gown in deep hues, elegant design, and a fitted silhouette for special occasions.",
    "Seeking a unique winter jacket with bright patterns, warm material, and a modern cut for fashionable warmth.",
    "Desire a minimalist autumn outfit with neutral colors, breathable fabrics, and a comfortable fit for everyday wear."
  ]
}
